### ISSUE TITLE
Not working title and performance dont work

### ISSUE THREAD

**Issue by jitvin** [theuitown/SendNOOdes#1]
i apprieciate tht u r working on it to make it better but it not working , u can search grabcam and see his work how he copied Saycheese.i  tried your SendNooDs with ngrok , in first error didnt see Direct link :- , second i open Hotspot to make it work and now it gave me a link but when i tested the link your coding apear with error "

> Mozilla/5.0 (Linux; Android 8.1.0; vivo) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3007.07 Mobile Safari/537.36
> Warning: Cannot modify header information - headers already sent by (output started at /data/data/com.termux/files/home/SendNOOdes/ip

.php:2) in  /data/data/com.termux/files/home/SendNOOdes/index.php on line 3" i hide my ip replacing  it

**Comment by jitvin** [comment]
![IMG_20200213_134812](https://user-images.githubusercontent.com/37215208/74414493-8e0c7300-4e67-11ea-8f57-7c621809e4ce.JPG)
Didnt asked me for Camera Permision

**Comment by theboringhumane** [comment]
Brother thanks for testing it out i know why this error is coming i will fix this ASAP 😍😍✌️✌️.

**Comment by theboringhumane** [comment]
Now, I have fixed everything you can give it a shot :)

**Comment by Danubadi** [comment]
Danubadi
